numericData <- c(10,20,30,40,50,60,70)
characterData <- c("abc","Hello World!","Armando","Loves","To","Eat","Chicken Nuggets")
logicalData <- c(TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE)
typeof(numericData)
typeof(characterData)
typeof(logicalData)
print(numericData)
print(characterData)
print(logicalData)
